### ISSUE TITLE
Items Birthcontrols

### ISSUE THREAD

**Issue by mirjamknook** [akocmark/Fertiller#1]
Hello,
The articles in the section birth controls has some display problem.
Sometimes the fertiller title screen shows up in the middle of the screen.
Mostly when I press the little button (in the description and instruction)
Is there a way how I can solve that.

And a second question : I like to make a translation for this app in Dutch. Is there a way u know how i can make translations for the birthcontrol.model.js, fertility.model etc...If the phone settings are on English or Dutch that it will display in the right language.

![10410226_10152523089649725_3462460400935614546_n](https://cloud.githubusercontent.com/assets/6861160/3386000/1e79d34c-fc70-11e3-9a26-5f76d7d4429e.jpg)

![moet vertaald worden 2](https://cloud.githubusercontent.com/assets/6861160/3386017/4109e230-fc70-11e3-935f-5c936b40a0db.png)

**Comment by akocmark** [comment]
I guess there is an issue on fixed positioning(the title screen or header) on different OS versions. especially when scrolling.

the current layout is somewhat like this:

```
<body> // this is where the scroll bar is attached
        <header/> // fixed position

        <content/> // gets scrolled

        <footer/> /// fixed position
</body>
```

restructure the layout like this:

```
<body> // make the body fits exactly on the viewport height, so it should not have scrollbars
        <header/> // fixed position

        <content/> // make this a scroll-able div, so you won't mess up the header and footer

        <footer/> /// fixed position
</body>
```

I haven't tried translating an app in to other languages yet. 
Maybe you could try this out
http://www.localeplanet.com/index.html

**Comment by mirjamknook** [comment]
The problem got fixed.

I added in the style css.
top: 0;

.nav-tab-bar { 
    height: 70px;
    background: #1f5b83;
    color: #DBD9DE;
    border-bottom: 1px solid #888;
    top: 0;

Still figuring out, how to do the translations.

![photo1](https://cloud.githubusercontent.com/assets/6861160/3466946/7e71e6da-0289-11e4-805e-852fd356b294.jpg)

**Comment by mirjamknook** [comment]
I would like to thank you for helping me out.
I have one last question.
The items in the nav-tab-bar how are they linked together?
Just tried to make an about.html but that doesn't work that way.
My knowledge of JS is absolutely zero.
The project is for a learning school program. So I wouldnt be using it for commercial market.

**Comment by akocmark** [comment]
No worries.
I can't understand what you want to do. maybe if you can provide screenshots like your previous post. I'll glady help :)

**Comment by akocmark** [comment]
and by the way, this is your site right? http://www.mistiek.nl
it's really cool. How can you write clever JS with zero knowledge? :D

**Comment by mirjamknook** [comment]
I'm trying to link the About page. 
From the header (nav-tab-bar) to the following window/page.
Perhaps you could give me a tip, on how to do it.

![menu](https://cloud.githubusercontent.com/assets/6861160/4146487/21f45514-340c-11e4-9f07-f9d285ba3bf9.jpg)

Actually my website is mostly written in HTML and PHP forms. The text is just sample text, cause it isn't finished yet.

**Comment by akocmark** [comment]
they're not linked automatically.. because they are not anchor tags (<a></a>)

the reason behind this is, browsers on mobile devices have a 300ms tap delay and it doesn't feel native that way..

the code to link a page is this..

```
$('.about_button').on('touchstart', function(e){  
    window.location.replace('about.html');
}); 
```

**Comment by mirjamknook** [comment]
Hello Mark,

I'am trying to figure out which IDE I like the best so far.
I have heard a lot of compliments with the program Intel XDK for beginners, here is an option to import phonegap/cordova projects.
But I cannot import the project because it is missing the index.html file, I tried it even with Phonegap. But I've got the same error. 
Do you have a clue, because in the most phonegap applications there is a index.html file.

Sorry for the many many bothered questions to you.
